### PR TITLE
Allows symfony 6

### PR DESCRIPTION
**Pull request by szappacosta**
breaking change: disallow symfony 4 for 5.4 LTS

### CODE REVIEW

**Comment by szappacosta** [comment]
@AntoineLelaisant @PedroTroller Hello french fellows, i'm having troubles fixing the type hinting error, since the interface is different between symfony 5.4 and 6.0 what it's the way to fix that ?

**Comment by PedroTroller** [comment]
:hand: 
It's because Symfony 6 is not compatible with php 7.4 anymore and it's using the `mixed` type. So I think we should drop support of php 7 to to be compatible with Symfony 6.

**Comment by szappacosta** [comment]
> ✋ It's because Symfony 6 is not compatible with php 7.4 anymore and it's using the `mixed` type. So I think we should drop support of php 7 to to be compatible with Symfony 6.

Thanks, i'll go forward this way.

**Comment by szappacosta** [comment]
Hello, i'm stuck again, i don't know if the phpspecs have to be updated, or if there is something else wrong in my symfony 6 update.

**Comment by szappacosta** [comment]
@PedroTroller Ping =)

**Comment by PedroTroller** [comment]
@szappacosta I've fixed the specs : https://github.com/KnpLabs/DictionaryBundle/pull/156
You an rebase and retry.

**Comment by PedroTroller** [comment]
BTW, why have you dropped support of Symfony 5.4 ?

**Comment by szappacosta** [comment]
@PedroTroller Fixed, sadly you cannot use php 8.1 for development some dev dependencies requires 8.0.*

**Comment by szappacosta** [comment]
@PedroTroller ready to review =)

**Review by PedroTroller — APPROVED** [review]

**Comment by PedroTroller** [comment]
:+1: thanks

phpspec will be compatible with php 8.1 really soon, so migration to php 8.1 will be possible

**Comment by szappacosta** [comment]
@PedroTroller Hello, what is the tagging policy on this project ? Is it possible to tag master to enjoy the new updates ? =

**Pull request merged**
