### PR TITLE
Add type to constraint violation if different from values.

### PR DESCRIPTION
**Pull request by vibby**
Avoid useless error message : «The key 0 doesn't exist in the given dictionary. 0,1,2 available»
Replace it with this : «The key 0 (string) doesn't exist in the given dictionary. 0,1,2 (integer) available»

### CODE REVIEW

**Comment by PedroTroller** [comment]
@vibby v3.1 has been released. Can you rebase your PR ?

**Comment by vibby** [comment]
Done

**Comment by vibby** [comment]
Can you please consider merging it @PedroTroller ?

**Comment by PedroTroller** [comment]
@vibby I think there is a problem. If you have a dictionary like
```
"foo" => "bar",
12 => null,
```
When you try to access the key `0`, you will have the error 
```
The key 0 (integer) doesn't exist in the given dictionary. foo, 12 (string) available
```
But the key `12` s not a string.

**Comment by vibby** [comment]
Maybe I am wrong @PedroTroller, but I think the method ```getKeys``` of interface ```Knp\DictionaryBundle\Dictionary``` always returns an array with integer keys (0, 1, 2…), not an associative array. Anyway, I can ensure it with a ```reset``` function

**Comment by PedroTroller** [comment]
True but you don't check the keys of the return of `getKeys` but the values.

**Comment by vibby** [comment]
I changed it to use the reset function. Is that ok this way ?

**Comment by PedroTroller** [comment]
@vibby no, the problem remains the same. Not all keys have the same type.

**Comment by PedroTroller** [comment]
How about this : https://github.com/KnpLabs/DictionaryBundle/pull/125/files ?

**Comment by vibby** [comment]
I got it. A proposal soon :)

**Comment by vibby** [comment]
Got it, it now search for the «same» key but in a different type

**Pull request closed without merging**
